---
title: "Tikz"
author: "Luiz Fernando Palin Droubi"
date: "09/12/2019"
output: 
  beamer_presentation:
    theme: Copenhagen
    includes:
      in_header: preamble.tex
      before_body: bbody.tex
    keep_tex: true
classoption: 8pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Tèsté

## animated

General form for the $F$ distribution with $\nu_1$ and $\nu_2$ degrees of
  freedom:
  \[
    f(F; \nu_1, \nu_2) = \frac{\Gamma\left(\frac{\nu_1+\nu_2}{2}\right)}
    {\Gamma\left(\frac{\nu_1}{2}\right)\Gamma\left(\frac{\nu_2}{2}\right)}
    \left(\frac{\nu_1}{\nu_2}\right)^{\frac{\nu_1}{2}}
    \frac{F^{\frac{\nu_1-2}{2}}}{\left[1 +
    \left(\frac{\nu_1}{\nu_2}\right)F\right]^{\frac{\nu_1+\nu_2}{2}}}
  \]

  Critical region for an $F$ test for various degrees of freedom:

  \begin{center}

  \begin{animateinline}[autoplay,palindrome,
    begin={\begin{tikzpicture}[yscale=4]},
    end={\stepcounter{cnt}\end{tikzpicture}}]{8}
    \fdst{5.3426}{4}{3}{6.6667};\newframe
    \fdst{4.1072}{4}{4}{6};\newframe
    \fdst{3.5202}{4}{5}{5.6};\newframe
    \fdst{3.1808}{4}{6}{5.3333};\newframe
    \fdst{2.9605}{4}{7}{5.1429};\newframe
    \fdst{2.8064}{4}{8}{5};\newframe
    \fdst{2.6927}{4}{9}{4.8889};\newframe
    \fdst{2.6053}{4}{10}{4.8};\newframe
    \fdst{2.5216}{5}{10}{10.3684};\newframe
    \fdst{2.6106}{5}{9}{10.7120};\newframe
    \fdst{2.7264}{5}{8}{11.1463};\newframe
    \fdst{2.8833}{5}{7}{11.7125};\newframe
    \fdst{3.1075}{5}{6}{12.4807};\newframe
    \fdst{3.4530}{5}{5}{13.5812};\newframe
    \fdst{4.0506}{5}{4}{15.2856};\newframe
    \fdst{5.3092}{5}{3}{18.2638};\newframe
    \fdst{5.2847}{6}{3}{52.5};\newframe
    \fdst{4.0097}{6}{4}{40.5};\newframe
    \fdst{3.4045}{6}{5}{34.02};\newframe
    \fdst{3.0546}{6}{6}{30};\newframe
    \fdst{2.8274}{6}{7}{27.2755};\newframe
    \fdst{2.6683}{6}{8}{25.3125};\newframe
    \fdst{2.5509}{6}{9}{23.8333};\newframe
    \fdst{2.4606}{6}{10}{22.6800};\newframe
    \fdst{2.4140}{7}{10}{50.4952};\newframe
    \fdst{2.5053}{7}{9}{54.1009};\newframe
    \fdst{2.6241}{7}{8}{58.8076};\newframe
    \fdst{2.7849}{7}{7}{65.1899};\newframe
    \fdst{3.0145}{7}{6}{74.2894};\newframe
    \fdst{3.3679}{7}{5}{88.1895};\newframe
    \fdst{3.9790}{7}{4}{111.6641};\newframe
    \fdst{5.2662}{7}{3}{158.1280};\newframe
    \fdst{5.2517}{8}{3}{497.7779};\newframe
    \fdst{3.9549}{8}{4}{320};\newframe
    \fdst{3.3393}{8}{5}{236.544};\newframe
    \fdst{2.9830}{8}{6}{189.6296};\newframe
    \fdst{2.7516}{8}{7}{160.0933};\newframe
    \fdst{2.5893}{8}{8}{140};\newframe
    \fdst{2.4694}{8}{9}{125.5418};\newframe
    \fdst{2.3772}{8}{10}{114.688};\newframe
    \fdst{2.3473}{9}{10}{266.0};\newframe
    \fdst{2.4403}{9}{9}{298.0};\newframe
    \fdst{2.5612}{9}{8}{341.7};\newframe
    \fdst{2.7247}{9}{7}{404.0};\newframe
    \fdst{2.9577}{9}{6}{498.7};\newframe
    \fdst{3.3163}{9}{5}{655.8};\newframe
    \fdst{3.9357}{9}{4}{941.5};\newframe
    \fdst{5.2400}{9}{3}{1633.2};
  \end{animateinline}
\end{center}

## animated 2

  Statistical power in hypothesis testing:

  \begin{animateinline}[autoplay,loop,
    begin={\begin{tikzpicture}[scale=1.3]},
    end={\stepcounter{cnt}\end{tikzpicture}}]{3}
    \distpic{0.5}{.346}{.654}
    \newframe
    \distpic{0.7}{.542}{.458}\newframe
    \distpic{0.9}{.727}{.273}\newframe
    \distpic{1.1}{.865}{.135}\newframe
    \distpic{1.3}{.946}{.054}\newframe
    \distpic{1.5}{.982}{.018}\newframe
    \distpic{1.7}{.995}{.005}\newframe
    \distpic{1.9}{.999}{.001}
  \end{animateinline}

## Bootstrap

\begin{tikzpicture}[scale=.85]

% style
\tikzstyle{rboule} = [circle,scale=0.7,ball color=red]
\tikzstyle{gboule} = [circle,scale=0.7,ball color=green]
\tikzstyle{bboule} = [circle,scale=0.7,ball color=blue]
\tikzstyle{nboule} = [circle,scale=0.7,ball color=black]
\tikzstyle{sample} = [->,thin]

% complete element space
\path[draw,<-,thick] (0,5.6) -- (4,5.6);
\path (6,5.6) node {Complete element space};
\path[draw,->,thick] (8,5.6) -- (12,5.6);

\path ( 0.00,5.25) node[bboule] (i01) {};
\path ( 0.25,5.25) node[rboule] (i02) {};
\path ( 0.50,5.25) node[gboule] (i03) {};
\path ( 0.75,5.25) node[bboule] (i04) {};
\path ( 1.00,5.25) node[rboule] (i05) {};
\path ( 1.25,5.25) node[bboule] (i06) {};
\path ( 1.50,5.25) node[bboule] (i07) {};
\path ( 1.75,5.25) node[rboule] (i08) {};
\path ( 2.00,5.25) node[bboule] (i09) {};
\path ( 2.25,5.25) node[rboule] (i10) {};
\path ( 2.50,5.25) node[bboule] (i11) {};
\path ( 2.75,5.25) node[bboule] (i12) {};
\path ( 3.00,5.25) node[nboule] (i13) {};
\path ( 3.25,5.25) node[rboule] (i14) {};
\path ( 3.50,5.25) node[bboule] (i15) {};
\path ( 3.75,5.25) node[bboule] (i16) {};
\path ( 4.00,5.25) node[rboule] (i17) {};
\path ( 4.25,5.25) node[rboule] (i18) {};
\path ( 4.50,5.25) node[bboule] (i19) {};
\path ( 4.75,5.25) node[bboule] (i20) {};
\path ( 5.00,5.25) node[rboule] (i21) {};
\path ( 5.25,5.25) node[bboule] (i22) {};
\path ( 5.50,5.25) node[rboule] (i23) {};
\path ( 5.75,5.25) node[bboule] (i24) {};
\path ( 6.00,5.25) node[bboule] (i25) {};
\path ( 6.25,5.25) node[rboule] (i26) {};
\path ( 6.50,5.25) node[rboule] (i27) {};
\path ( 6.75,5.25) node[gboule] (i28) {};
\path ( 7.00,5.25) node[rboule] (i29) {};
\path ( 7.25,5.25) node[bboule] (i30) {};
\path ( 7.50,5.25) node[bboule] (i31) {};
\path ( 7.75,5.25) node[nboule] (i32) {};
\path ( 8.00,5.25) node[bboule] (i33) {};
\path ( 8.25,5.25) node[rboule] (i34) {};
\path ( 8.50,5.25) node[gboule] (i35) {};
\path ( 8.75,5.25) node[bboule] (i36) {};
\path ( 9.00,5.25) node[bboule] (i37) {};
\path ( 9.25,5.25) node[rboule] (i38) {};
\path ( 9.50,5.25) node[bboule] (i39) {};
\path ( 9.75,5.25) node[rboule] (i40) {};
\path (10.00,5.25) node[bboule] (i41) {};
\path (10.25,5.25) node[rboule] (i42) {};
\path (10.50,5.25) node[bboule] (i43) {};
\path (10.75,5.25) node[bboule] (i44) {};
\path (11.00,5.25) node[rboule] (i45) {};
\path (11.25,5.25) node[nboule] (i46) {};
\path (11.50,5.25) node[rboule] (i47) {};
\path (11.75,5.25) node[bboule] (i48) {};
\path (12.00,5.25) node[bboule] (i49) {};

% title initial sample
\path (3.5,3.75) node[anchor=east] 
	{\parbox{0.15\textwidth}{\centering initial sample with N elements}};

% labels
\path (3.5,3)   node[anchor=east] {1};
\path (3.5,2.5) node[anchor=east] {2};
\path (3.5,2.0) node[anchor=east] {3};
\path (3.5,1.5) node[anchor=east] {4};
\path (3.5,0.5) node[anchor=east] {$N_b$};

\path (3.5,1) node[anchor=east] {$\vdots$};
\path[draw,dashed] (4,1) -- (8.25,1);

\path[draw,<->,thick] (2.9,0.5) -- (2.9,3) node[anchor=east,pos=0.5] 
	{\parbox{0.1\textwidth}{\centering $N_b$ \textit{bootstrap} samples}};

% initial sample
\path ( 3.75,3.75) node[bboule] (j01) {};               
\path ( 4.00,3.75) node[bboule] (j02) {};               
\path ( 4.25,3.75) node[rboule] (j03) {};               
\path ( 4.50,3.75) node[rboule] (j04) {};               
\path ( 4.75,3.75) node[rboule] (j05) {};               
\path ( 5.00,3.75) node[nboule] (j06) {};               
\path ( 5.25,3.75) node[bboule] (j07) {};               
\path ( 5.50,3.75) node[rboule] (j08) {};               
\path ( 5.75,3.75) node[bboule] (j09) {};               
\path ( 6.00,3.75) node[bboule] (j10) {};               
\path ( 6.25,3.75) node[bboule] (j11) {};               
\path ( 6.50,3.75) node[rboule] (j12) {};               
\path ( 6.75,3.75) node[gboule] (j13) {};               
\path ( 7.00,3.75) node[rboule] (j14) {};               
\path ( 7.25,3.75) node[gboule] (j15) {};               
\path ( 7.50,3.75) node[bboule] (j16) {};               
\path ( 7.75,3.75) node[rboule] (j17) {};               
\path ( 8.00,3.75) node[rboule] (j18) {};               
\path ( 8.25,3.75) node[bboule] (j19) {};               
\path ( 8.50,3.75) node[rboule] (j20) {}; 

% arrows from the complete space to the initial sample
\path[sample] (i01.south) edge[out=-60,in=120] (j01.north west);
\path[sample] (i04.south) edge[out=-60,in=120] (j02.north west);
\path[sample] (i05.south) edge[out=-60,in=120] (j03.north west);
\path[sample] (i08.south) edge[out=-60,in=120] (j04.north west);
\path[sample] (i10.south) edge[out=-60,in=120] (j05.north west);
\path[sample] (i13.south) edge[out=-60,in=120] (j06.north west);
\path[sample] (i16.south) edge[out=-90,in=90] (j07.north);
\path[sample] (i18.south) edge[out=-90,in=90] (j08.north);
\path[sample] (i20.south) edge[out=-90,in=90] (j09.north);
\path[sample] (i24.south) edge[out=-90,in=90] (j10.north);
\path[sample] (i25.south) edge[out=-90,in=90] (j11.north);
\path[sample] (i27.south) edge[out=-90,in=90] (j12.north);
\path[sample] (i28.south) edge[out=-90,in=90] (j13.north);
\path[sample] (i34.south) edge[out=-90,in=90] (j14.north);
\path[sample] (i35.south) edge[out=-90,in=90] (j15.north);
\path[sample] (i37.south) edge[out=-90,in=60] (j16.north east);
\path[sample] (i40.south) edge[out=-90,in=60] (j17.north east);
\path[sample] (i42.south) edge[out=-90,in=60] (j18.north east);
\path[sample] (i44.south) edge[out=-90,in=60] (j19.north east);
\path[sample] (i47.south) edge[out=-90,in=60] (j20.north east);

% bootstrap 1
\path ( 3.75, 3.0) node[bboule] {};                    
\path ( 4.00, 3.0) node[bboule] {};                    
\path ( 4.25, 3.0) node[bboule] {};                    
\path ( 4.50, 3.0) node[gboule] {};                    
\path ( 4.75, 3.0) node[rboule] {};                    
\path ( 5.00, 3.0) node[bboule] {};                    
\path ( 5.25, 3.0) node[gboule] {};                    
\path ( 5.50, 3.0) node[bboule] {};                    
\path ( 5.75, 3.0) node[rboule] {};                    
\path ( 6.00, 3.0) node[rboule] {};                    
\path ( 6.25, 3.0) node[bboule] {};                    
\path ( 6.50, 3.0) node[rboule] {};                    
\path ( 6.75, 3.0) node[rboule] {};                    
\path ( 7.00, 3.0) node[rboule] {};                    
\path ( 7.25, 3.0) node[bboule] {};                    
\path ( 7.50, 3.0) node[nboule] {};                    
\path ( 7.75, 3.0) node[rboule] {};                    
\path ( 8.00, 3.0) node[rboule] {};                    
\path ( 8.25, 3.0) node[gboule] {};                    
\path ( 8.50, 3.0) node[gboule] (b1) {};                    
                                                       
% bootstrap 2
\path ( 3.75, 2.5) node[bboule] {};                    
\path ( 4.00, 2.5) node[bboule] {};                    
\path ( 4.25, 2.5) node[rboule] {};                    
\path ( 4.50, 2.5) node[nboule] {};                    
\path ( 4.75, 2.5) node[rboule] {};                    
\path ( 5.00, 2.5) node[bboule] {};                    
\path ( 5.25, 2.5) node[bboule] {};                    
\path ( 5.50, 2.5) node[rboule] {};                    
\path ( 5.75, 2.5) node[rboule] {};                    
\path ( 6.00, 2.5) node[rboule] {};                    
\path ( 6.25, 2.5) node[bboule] {};                    
\path ( 6.50, 2.5) node[rboule] {};                    
\path ( 6.75, 2.5) node[rboule] {};                    
\path ( 7.00, 2.5) node[rboule] {};                    
\path ( 7.25, 2.5) node[rboule] {};                    
\path ( 7.50, 2.5) node[rboule] {};                    
\path ( 7.75, 2.5) node[bboule] {};                    
\path ( 8.00, 2.5) node[bboule] {};                    
\path ( 8.25, 2.5) node[bboule] {};                    
\path ( 8.50, 2.5) node[bboule] (b2) {};                    
                                                       
% bootstrap 3
\path ( 3.75, 2.0) node[rboule] {};                    
\path ( 4.00, 2.0) node[bboule] {};                    
\path ( 4.25, 2.0) node[rboule] {};                    
\path ( 4.50, 2.0) node[rboule] {};                    
\path ( 4.75, 2.0) node[bboule] {};                    
\path ( 5.00, 2.0) node[bboule] {};                    
\path ( 5.25, 2.0) node[bboule] {};                    
\path ( 5.50, 2.0) node[bboule] {};                    
\path ( 5.75, 2.0) node[rboule] {};                    
\path ( 6.00, 2.0) node[rboule] {};                    
\path ( 6.25, 2.0) node[gboule] {};                    
\path ( 6.50, 2.0) node[gboule] {};                    
\path ( 6.75, 2.0) node[rboule] {};                    
\path ( 7.00, 2.0) node[rboule] {};                    
\path ( 7.25, 2.0) node[nboule] {};                    
\path ( 7.50, 2.0) node[bboule] {};                    
\path ( 7.75, 2.0) node[rboule] {};                    
\path ( 8.00, 2.0) node[bboule] {};                    
\path ( 8.25, 2.0) node[rboule] {};                    
\path ( 8.50, 2.0) node[nboule] (b3) {};

% bootstrap 4
\path ( 3.75, 1.5) node[nboule] {};
\path ( 4.00, 1.5) node[bboule] {};
\path ( 4.25, 1.5) node[rboule] {};
\path ( 4.50, 1.5) node[gboule] {};
\path ( 4.75, 1.5) node[bboule] {};
\path ( 5.00, 1.5) node[gboule] {};
\path ( 5.25, 1.5) node[bboule] {};
\path ( 5.50, 1.5) node[rboule] {};
\path ( 5.75, 1.5) node[bboule] {};
\path ( 6.00, 1.5) node[rboule] {};
\path ( 6.25, 1.5) node[gboule] {};
\path ( 6.50, 1.5) node[nboule] {};
\path ( 6.75, 1.5) node[bboule] {};
\path ( 7.00, 1.5) node[rboule] {};
\path ( 7.25, 1.5) node[rboule] {};
\path ( 7.50, 1.5) node[rboule] {};
\path ( 7.75, 1.5) node[rboule] {};
\path ( 8.00, 1.5) node[bboule] {};
\path ( 8.25, 1.5) node[bboule] {};
\path ( 8.50, 1.5) node[gboule] (b4) {};

% bootstrap N
\path ( 3.75, 0.5) node[nboule] {};
\path ( 4.00, 0.5) node[gboule] {};
\path ( 4.25, 0.5) node[rboule] {};
\path ( 4.50, 0.5) node[rboule] {};
\path ( 4.75, 0.5) node[bboule] {};
\path ( 5.00, 0.5) node[rboule] {};
\path ( 5.25, 0.5) node[bboule] {};
\path ( 5.50, 0.5) node[gboule] {};
\path ( 5.75, 0.5) node[bboule] {};
\path ( 6.00, 0.5) node[bboule] {};
\path ( 6.25, 0.5) node[gboule] {};
\path ( 6.50, 0.5) node[rboule] {};
\path ( 6.75, 0.5) node[rboule] {};
\path ( 7.00, 0.5) node[gboule] {};
\path ( 7.25, 0.5) node[bboule] {};
\path ( 7.50, 0.5) node[bboule] {};
\path ( 7.75, 0.5) node[bboule] {};
\path ( 8.00, 0.5) node[rboule] {};
\path ( 8.25, 0.5) node[bboule] {};
\path ( 8.50, 0.5) node[gboule] (bN) {};

% arrows
\path[sample] (j20.east) edge [out=0, in=60] (b1.east);
\path[sample] (j20.east) edge [out=0, in=60] (b2.east);
\path[sample] (j20.east) edge [out=0, in=60] (b3.east);
\path[sample] (j20.east) edge [out=0, in=60] (b4.east);
\path[sample] (j20.east) edge [out=0, in=60] (bN.east);

\end{tikzpicture}

## Bootstrap theoreme

\begin{center}

\begin{tikzpicture}

\definecolor{monred}{rgb}{0.79 0.0 0.1}

\tikzstyle{rec} = [rectangle,rounded corners,ultra thick,draw=monred!90,fill=white] 

\node[rec,text=black!80,inner sep=3mm,drop shadow] (th)
	{\parbox{0.6\textwidth}{
	When N tend to infinity, the distribution of average values computed from bootstrap samples
	is equal to the distribution of average values obtained from ALL samples with N elements
	which can be constructed from the complete space. Thus the width of the distribution gives
	an evaluation of the sample quality.}};

\node[rec,text=monred!95,anchor=south west,xshift=3mm,yshift=-1mm] 
	at (th.north west) {\small Theorem \scriptsize (B. Efron, Ann. Statist. 1979)};

\end{tikzpicture}

\end{center}


## TT

\begin{center}
\begin{tikzpicture}
\draw[<->] (6,0) node[below]{$q$} -- (0,0) --
(0,6) node[left]{$V(q)$};
\draw[very thick] (0,0) to [out=90,in=145] (5,4.5);
\end{tikzpicture}
\end{center}


## Normal Distribution

\begin{tikzpicture}[scale=1.25]
    \colorlet{col1}{blue!70}
    \colorlet{col2}{blue!60}
    \colorlet{col3}{blue!50}
    \colorlet{col4}{blue!40}
   %\draw [help lines] (-4.25,-1.25) grid (4.25,1.5);
   %\draw [help lines,step=0.25cm] (-2.99,0) grid (2.99,0.99);

   \draw[->] (0,-1.25) -- (0,1.5) node [above]
     {$\displaystyle
        \frac{1}{\sigma\sqrt{2\pi}}\exp\biggl(\frac{-x^2}{2\sigma^2}\biggr)
     $};

   \begin{scope}[smooth,draw=gray!20,y=0.3989422804cm]
        \filldraw [fill=col3] plot[id=f1,domain=-3:-2] function {exp(-x*x/2)}
            -- (-2,0) -- (-3,0) -- cycle;
        \filldraw [fill=col2] plot[id=f2,domain=-2:-1] function {exp(-x*x/2)}
            -- (-1,0) -- (-2,0) -- cycle;
        \filldraw [fill=col1] plot[id=f3,domain=-1:0]  function {exp(-x*x/2)}
            -- (0,0)  -- (-1,0) -- cycle;
        \filldraw [fill=col1] plot[id=f4,domain=0:1] function {exp(-x*x/2)}
            -- (1,0)  --  (0,0) -- cycle;
        \filldraw [fill=col2] plot[id=f5,domain=1:2] function {exp(-x*x/2)}
            -- (2,0)  -- (1,0) -- cycle;
        \filldraw [fill=col3] plot[id=f6,domain=2:3] function {exp(-x*x/2)}
            -- (3,0)  -- (2,0) -- cycle;
        \draw[black] plot[id=f7,domain=-4.25:4.25,samples=100]
            function {exp(-x*x/2)};
   \end{scope}
       \draw[->] (-4.25,0) -- (4.25,0) node [right] {$x$};

    \foreach \pos/\label in {-3/$-3\sigma$,-2/$-2\sigma$,-1/$-\sigma$,
            1/$\sigma$,2/$2\sigma$,3/$3\sigma$}
        \draw (\pos,0) -- (\pos,-0.1) (\pos cm,-3ex) node
            [anchor=base,fill=white,inner sep=1pt]  {\label};

    \draw (-0.1,1) -- (.1,1) node [right,fill=white,inner sep=1pt] {$\sigma$};

    \foreach \pos/\percent/\height in {1/34/0.5,2/14/0.25,3/2/0.125,4/0.1/0.1}
    {
      \node[text=col\pos,anchor=base,yshift=2pt,xshift=-0.625cm,
        fill=white,inner sep=1pt] at (\pos,\height) {$\percent\%$};
      \node[text=col\pos,anchor=base,yshift=2pt,xshift=.625cm,
        fill=white,inner sep=1pt]  at (-\pos,\height) {$\percent\%$};
    }
\end{tikzpicture}

## Teste

\begin{center}
\begin{tikzpicture}[domain=0:4]
    \draw[very thin,color=gray] (-0.1,-1.1) grid (3.9,3.9);
    \draw[->] (-0.2,0) -- (4.2,0) node[right] {$x$};
    \draw[->] (0,-1.2) -- (0,4.2) node[above] {$f(x)$};
    \draw[color=red] plot[id=x] function{x} 
        node[right] {$f(x) =x$};
    \draw[color=blue] plot[id=sin] function{sin(x)} 
        node[right] {$f(x) = \sin x$};
    \draw[color=orange] plot[id=exp] function{0.05*exp(x)} 
        node[right] {$f(x) = \frac{1}{20} \mathrm e^x$};
\end{tikzpicture}
\end{center}
